<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['base_url'] = 'http://'.$_SERVER['HTTP_HOST'].'/AI-Wholesale';
date_default_timezone_set("Asia/Kolkata");
$config['index_page'] = '';
$config['uri_protocol'] = 'AUTO';
$config['url_suffix'] = '';
$config['language'] = 'english';
$config['charset'] = 'UTF-8';
$config['enable_hooks'] = FALSE;
$config['subclass_prefix'] = 'MY_';
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';
$config['log_threshold'] = 1;
$config['log_path'] = '';
$config['log_date_format'] = 'Y-m-d H:i:s';
$config['cache_path'] = '';
$config['sess_driver'] = 'files';
$config['encryption_key'] = 'AIWholesale2024SecretKey!@#$%^&*';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_expire_on_close'] = TRUE;
$config['sess_encrypt_cookie'] = FALSE;
$config['sess_use_database'] = FALSE;
$config['sess_table_name'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_match_useragent'] = TRUE;
$config['sess_time_to_update'] = 300;
$config['sess_save_path'] = sys_get_temp_dir();
$config['cookie_prefix'] = '';
$config['cookie_domain'] = '';
$config['cookie_path'] = '/';
$config['cookie_secure'] = FALSE;
$config['global_xss_filtering'] = FALSE;
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['compress_output'] = FALSE;
$config['time_reference'] = 'local';
$config['rewrite_short_tags'] = FALSE;
$config['proxy_ips'] = '';

define('SITE_NAME', 'AI Wholesale');
define('BASE_URL', $config['base_url']);
define('ADMIN_EMAIL', 'admin@aiwholesale.com');
define('CURRENT_DATE', date('Y-m-d'));
define('PER_PAGE_DATA', 12);
define('SHOW_ADMIN_PROFILE_PATH', BASE_URL.'/uploads/users/');
define('SHOW_BANNER_PATH', BASE_URL.'/uploads/banners/');
define('SHOW_CATEGORY_PATH', BASE_URL.'/uploads/categories/');
define('SHOW_PRODUCT_PATH', BASE_URL.'/uploads/products/');
define('SHOW_TESTIMONIAL_PATH', BASE_URL.'/uploads/testimonials/');
define('CURRENCY_SYMBOL', '£');
// define('STRIPE_PUBLISHABLE_KEY', 'pk_test_51TY9tX2fs6R6o5tbZ2sgsDgZkwqTRo1HxCAF0eausXsknsxw8EAXpeQbtorudsj2vpXR2rgKza1U9gfHphO2uJsB00dA1F1i1Q');
// define('STRIPE_SECRET_KEY', 'sk_test_51TY9tX2fs6R6o5tb6CdOMrUsB9uPk0ZKyvHpP6tFNsGmPTRrtUNNrMh10wtvAvxQ1dv3dQDPGJ2RSDJFhRsJ7Lln007LmGrnrB');
define('UPLOAD_PRODUCT_PATH', dirname($_SERVER['SCRIPT_FILENAME']).'/uploads/products/');
define('UPLOAD_BANNER_PATH', dirname($_SERVER['SCRIPT_FILENAME']).'/uploads/banners/');
define('UPLOAD_PRODUCT_NO_IMAGE', BASE_URL.'/uploads/');
define('ISSMTP', 0);
define('SMTP_PROTOCOL', 'smtp');
define('SMTP_HOST', 'ssl://smtp.gmail.com');
define('SMTP_PORT', 465);
define('SMTP_USER', 'admin@aiwholesale.com');
define('SMTP_PASS', '');
define('MAIL_TYPE', 'html');
